In [1]:
# Import required modules

import numpy as np
import pandas as pd
import statistics

from collections import Counter
from tqdm import tqdm

In [2]:
# Import GEO reference data

# import table with accession, platform, and series
geoAPS = pd.read_csv('../data/geo_samples.csv')

# import table with datasets IDs
geoSeries = pd.read_csv('../data/geo_series.csv', low_memory = False)
geoSeries.rename(columns={'Accession':'Series'}, inplace = True)

# add datasets column by merging
allData = pd.merge(geoAPS, geoSeries, how = 'outer', on = 'Series')
geoReference = allData[['Series', 'Accession', 'Platform', 'Datasets']].drop_duplicates()

In [3]:
sra_reference_path = '../data/sra_complete_runs.csv'
# Only read columns needed downstream to save memory and time
SRA_COLS = ['Run', 'SRAStudy', 'Experiment', 'BioProject', 'Submission', 'Sample',
            'ReleaseDate', 'Model', 'LibraryStrategy', 'ScientificName',
            'bases', 'avgLength', 'Consent']
chunks = []
for chunk in pd.read_csv(sra_reference_path, chunksize=500_000,
                          usecols=lambda c: c in SRA_COLS, low_memory=False):
    chunks.append(chunk)
result_df = pd.concat(chunks, ignore_index=True)
print(f"SRA runs loaded: {result_df.shape}")

In [4]:
# SRA loading done in cell above

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: g1k_pop_code, 1: source, 2: g1k_analysis_group, 3: Subject_ID, 4: Sex, 5: Affection_Status, 6: Analyte_Type, 7: Histological_Type, 8: Body_Site, 9: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

1

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: g1k_pop_code, 1: source, 2: g1k_analysis_group, 3: Subject_ID, 4: Disease, 5: Affection_Status, 6: Analyte_Type, 7: Histological_Type, 8: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

2
3

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: AssemblyName) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: LibraryName) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

20

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: AssemblyName, 1: LibraryName) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

21
22
23
24
25
26
27
28

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: LibraryName, 1: Subject_ID, 2: Sex, 3: Analyte_Type, 4: Histological_Type, 5: Body_Site, 6: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

29

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: AssemblyName, 1: g1k_pop_code, 2: source, 3: g1k_analysis_group, 4: Subject_ID, 5: Sex, 6: Disease, 7: Analyte_Type, 8: Histological_Type, 9: Body_Site, 10: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

30

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: AssemblyName, 1: g1k_pop_code, 2: source, 3: g1k_analysis_group, 4: Subject_ID, 5: Sex, 6: Analyte_Type, 7: Histological_Type, 8: Body_Site, 9: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

31

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: AssemblyName, 1: LibraryName, 2: g1k_pop_code, 3: source, 4: g1k_analysis_group, 5: Subject_ID, 6: Sex, 7: Disease, 8: Analyte_Type, 9: Histological_Type, 10: Body_Site, 11: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

32
33
34

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: AssemblyName, 1: g1k_pop_code, 2: source, 3: g1k_analysis_group, 4: Subject_ID, 5: Analyte_Type, 6: Histological_Type, 7: Body_Site, 8: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

35

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: g1k_pop_code, 1: source, 2: g1k_analysis_group, 3: Subject_ID, 4: Histological_Type, 5: Body_Site) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

36

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: g1k_pop_code, 1: source, 2: g1k_analysis_group, 3: Subject_ID, 4: Analyte_Type, 5: Histological_Type, 6: Body_Site, 7: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

37

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: g1k_pop_code, 1: source, 2: g1k_analysis_group, 3: Analyte_Type, 4: Histological_Type, 5: Body_Site, 6: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

38

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: AssemblyName, 1: g1k_pop_code, 2: source, 3: g1k_analysis_group, 4: Subject_ID, 5: Affection_Status, 6: Analyte_Type, 7: Histological_Type, 8: Body_Site, 9: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

39

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: AssemblyName, 1: Subject_ID, 2: Sex, 3: Analyte_Type, 4: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

40
41
42

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: g1k_pop_code, 1: source, 2: g1k_analysis_group, 3: Subject_ID, 4: Affection_Status, 5: Analyte_Type, 6: Histological_Type, 7: Body_Site, 8: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

43

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: g1k_pop_code, 1: source, 2: g1k_analysis_group, 3: Subject_ID, 4: Disease, 5: Histological_Type, 6: Body_Site) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

44

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: g1k_pop_code, 1: source, 2: g1k_analysis_group, 3: Subject_ID, 4: Histological_Type) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

45

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: AssemblyName, 1: Study_Pubmed_id, 2: g1k_pop_code, 3: source, 4: g1k_analysis_group, 5: Subject_ID, 6: Sex, 7: Analyte_Type, 8: Histological_Type, 9: Body_Site, 10: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

46
47

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: g1k_pop_code, 1: source, 2: g1k_analysis_group, 3: Subject_ID, 4: Sex, 5: Analyte_Type, 6: Histological_Type, 7: Body_Site, 8: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

48

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: AssemblyName, 1: Subject_ID, 2: Sex, 3: Analyte_Type, 4: Histological_Type, 5: Body_Site, 6: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

49

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: AssemblyName, 1: LibraryName, 2: Subject_ID, 3: Sex, 4: Analyte_Type, 5: Histological_Type, 6: Body_Site, 7: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

50

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: AssemblyName, 1: LibraryName, 2: g1k_pop_code, 3: source, 4: g1k_analysis_group, 5: Subject_ID, 6: Sex, 7: Analyte_Type, 8: Histological_Type, 9: Body_Site, 10: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

51
52
53

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: AssemblyName, 1: g1k_pop_code, 2: source, 3: g1k_analysis_group, 4: Subject_ID, 5: Sex, 6: Affection_Status, 7: Analyte_Type, 8: Histological_Type, 9: Body_Site, 10: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

54
55
56
57
58
59
60

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: AssemblyName, 1: Subject_ID, 2: Sex, 3: Analyte_Type, 4: Body_Site, 5: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

61
62

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: AssemblyName, 1: SampleName, 2: Subject_ID, 3: Sex, 4: Analyte_Type, 5: Body_Site, 6: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

63
64
65

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: Study_Pubmed_id, 1: g1k_pop_code, 2: source, 3: g1k_analysis_group, 4: Subject_ID, 5: Analyte_Type, 6: Histological_Type, 7: Body_Site, 8: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

66

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: g1k_pop_code, 1: source, 2: g1k_analysis_group, 3: Disease, 4: Histological_Type) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

67
68
69
70
71
72
73

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: Study_Pubmed_id, 1: g1k_pop_code, 2: source, 3: g1k_analysis_group) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

74

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: g1k_pop_code, 1: source, 2: g1k_analysis_group, 3: Sex, 4: Affection_Status, 5: Analyte_Type, 6: Histological_Type, 7: Body_Site, 8: dbgap_study_accession) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

75
76

/tmp/ipykernel_3728001/1696761591.py:1: DtypeWarning: Columns (0: g1k_pop_code, 1: source, 2: g1k_analysis_group) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iterator:

77

In [5]:
result_df.shape

(7641720, 47)

In [ ]:
# (5041744, 47)

In [6]:
sraReference = result_df

In [7]:
# import data scraped from PubMed

pmcData = pd.read_csv('../data/pre_filter_matrix.csv')
pmcData

               journal_name       pmc_id     accession
0             SAGE Open Med  PMC12833201      GSE85217
1             SAGE Open Med  PMC12833201      GSE85212
2                Genome Med  PMC12833949     GSE128639
3                Genome Med  PMC12833949     GSE214979
4                Genome Med  PMC12833949     GSE171964
...                     ...          ...           ...
793097  Nat Struct Mol Biol   PMC2722042      GSE14884
793098              bioRxiv  PMC12874027     GSE138852
793099          Commun Biol  PMC12647768  PRJNA1341055
793100          BMC Geriatr  PMC12681135  PRJNA1255383
793101       Nat Biotechnol  PMC12339006  PRJNA1004618

[793102 rows x 3 columns]

In [8]:
pmcData.columns = ['journal', 'pmc_ID', 'accession']

In [9]:
# Merge GEO accessions with reference data, convert to Series

# match series first
se = pd.merge(pmcData, geoReference['Series'].drop_duplicates(), how = 'left',
            left_on = 'accession', right_on = 'Series')
pmcData = se.rename(columns = {'Series': 'Series_result'})

# match each other style of GEO ID
# NOTE: 'Platform' (GPL) is intentionally excluded — one platform maps to thousands
# of series, causing false dataset attribution (e.g. all GPL570 -> GSE100014)
for col in ['Accession', 'Datasets']:
    pmcData = pd.merge(pmcData, geoReference[['Series', col]].drop_duplicates(subset = col), how = 'left', 
            left_on = 'accession', right_on = col)
    label = col + '_result'
    pmcData = pmcData.rename(columns = {'Series': label})

# combine all GEO series match columns into one aggregate GEO series column, clean up
pmcData['geoSeries'] = pmcData['Series_result'].fillna(pmcData['Accession_result']).fillna(pmcData['Datasets_result'])
pmcData = pmcData.drop(labels = ['Accession', 'Datasets',
                           'Series_result', 'Accession_result',
                           'Datasets_result'], axis = 1)
pmcData_geoMerged = pmcData
pmcData_geoMerged

                    journal       pmc_ID     accession  geoSeries
0             SAGE Open Med  PMC12833201      GSE85217   GSE85217
1             SAGE Open Med  PMC12833201      GSE85212   GSE85212
2                Genome Med  PMC12833949     GSE128639  GSE128639
3                Genome Med  PMC12833949     GSE214979  GSE214979
4                Genome Med  PMC12833949     GSE171964  GSE171964
...                     ...          ...           ...        ...
793097  Nat Struct Mol Biol   PMC2722042      GSE14884   GSE14884
793098              bioRxiv  PMC12874027     GSE138852  GSE138852
793099          Commun Biol  PMC12647768  PRJNA1341055        NaN
793100          BMC Geriatr  PMC12681135  PRJNA1255383        NaN
793101       Nat Biotechnol  PMC12339006  PRJNA1004618        NaN

[793102 rows x 4 columns]

In [10]:
# merge SRA accessions with reference data, convert to Study

# match SRA Study IDs first
st = pd.merge(pmcData_geoMerged, sraReference['SRAStudy'].drop_duplicates(), how = 'left',
            left_on = 'accession', right_on = 'SRAStudy')
pmcData = st.rename(columns = {'SRAStudy': 'Study_result'})

# match every other style of SRA ID
for col in ['Run', 'Experiment', 'BioProject', 'Submission', 'Sample']:
    pmcData = pd.merge(pmcData, sraReference[['SRAStudy', col]].drop_duplicates(subset = [col]), how = 'left',
                      left_on = 'accession', right_on = col)
    label = col + '_result'
    pmcData = pmcData.rename(columns = {'SRAStudy': label})

# combine all SRA Study matches into one aggregate column, clean up
pmcData['sraStudy'] = pmcData['Study_result'].fillna(pmcData['Run_result']).fillna(pmcData['Experiment_result']).fillna(pmcData['BioProject_result']).fillna(pmcData['Submission_result']).fillna(pmcData['Sample_result'])
pmcData = pmcData.drop(labels = ['Run', 'Experiment', 'BioProject', 'Submission', 'Sample',
                                'Study_result', 'Run_result', 'Experiment_result', 'BioProject_result',
                                'Submission_result', 'Sample_result'], axis = 1)

pmcData_sraMerged = pmcData
pmcData_sraMerged.sample(25)

,journal,pmc_ID,accession,geoSeries,sraStudy
639136,Front Cell Infect Microbiol,PMC7959850,GSE36552,GSE36552,NaN
618292,Open Biol,PMC7776570,SRR7008199,NaN,SRP140470
456791,Genome Biol,PMC10031921,GSE127134,GSE127134,NaN
276729,J Biol Chem,PMC9287136,GSE89212,GSE89212,NaN
418956,Curr Biol,PMC10234599,PRJNA716780,NaN,NaN
286152,Stem Cell Reports,PMC10828684,PRJNA1000913,NaN,NaN
257729,Cell Rep,PMC8006859,GSE144372,GSE144372,NaN
772721,Sci Rep,PMC5481429,SRR1220398,NaN,SRP000941
247616,Medicine (Baltimore),PMC7593045,GSE112790,GSE112790,NaN
665510,Nucleic Acids Res,PMC13010144,GSE201000,GSE201000,NaN
370201,J Biomed Sci,PMC8973879,GSE18842,GSE18842,NaN
361,J Immunol,PMC12856555,GSE290455,GSE290455,NaN
425718,BMC Biol,PMC10845735,PRJNA792297,NaN,NaN
393938,Front Immunol,PMC10627007,GSE207015,GSE207015,NaN
433919,Nucleic Acids Res,PMC10783523,PRJNA929424,NaN,NaN
248005,Onco Targets Ther,PMC7250301,GSE29623,GSE29623,NaN
597939,PLoS One,PMC7067429,PRJNA407816,NaN,SRP123679
758103,PeerJ,PMC5732540,SRS2685506,NaN,SRP124961
471638,Cell Death Dis,PMC9617940,GSE178755,GSE178755,NaN
179593,PLoS Comput Biol,PMC6363223,PRJNA276699,NaN,NaN
176896,PLoS Genet,PMC6166978,ERS177320,NaN,ERP001813
443421,Cell Rep Methods,PMC10261927,SRP348989,NaN,SRP348989
500555,Front Immunol,PMC9437322,GSE42568,GSE42568,NaN
514823,Aging (Albany NY),PMC9004575,GPL16686,GSE100178,NaN
7824,PLoS One,PMC3520972,GSE6768,GSE6768,NaN

In [11]:
# combine GEO Series hits and SRA study hits into one converted accession column
pmcData['converted_accession'] = pmcData_sraMerged['geoSeries'].fillna(pmcData_sraMerged['sraStudy'])
pmcData = pmcData.drop(labels = ['geoSeries', 'sraStudy'], axis = 1)
pmcData

                    journal       pmc_ID     accession converted_accession
0             SAGE Open Med  PMC12833201      GSE85217            GSE85217
1             SAGE Open Med  PMC12833201      GSE85212            GSE85212
2                Genome Med  PMC12833949     GSE128639           GSE128639
3                Genome Med  PMC12833949     GSE214979           GSE214979
4                Genome Med  PMC12833949     GSE171964           GSE171964
...                     ...          ...           ...                 ...
793097  Nat Struct Mol Biol   PMC2722042      GSE14884            GSE14884
793098              bioRxiv  PMC12874027     GSE138852           GSE138852
793099          Commun Biol  PMC12647768  PRJNA1341055           SRP630989
793100          BMC Geriatr  PMC12681135  PRJNA1255383           SRP581200
793101       Nat Biotechnol  PMC12339006  PRJNA1004618           SRP454660

[793102 rows x 4 columns]

In [ ]:
# clean out garbage converted_accession entries, and rows that didn't map to a converted_accession

# Drop rows where the original accession was a GPL (platform) ID — these get falsely
# mapped to GSE series IDs through the geoReference merge and slip past the filter below
pmcData = pmcData[~pmcData['accession'].str.startswith('GPL', na=False)]

w = []
for a in pmcData['converted_accession']:
    if type(a) == str:
        if a[0:3] != 'GSE' and a[1:3] != 'RP':
                w.append(a)
w.append(np.nan)
        
pmcData = pmcData[~pmcData.converted_accession.isin(w)]
pmcData

In [13]:
# perform QC with gold standard from Penn group (Casey + Kurt)
gsPMC = pd.read_table("/home/nicolaedrabcinski/open-science-analytics/data/pubmed_mappings.tsv")
gsPMC.columns = ["SRA_accession_code", "GEO_accession_code", "pm_ID", "pmc_ID"]
gsPMC

      SRA_accession_code GEO_accession_code       pm_ID      pmc_ID
0              SRP111833          GSE101341  29535194.0  PMC5850328
1              ERP108370                NaN         NaN         NaN
2              SRP062170           GSE71840  27780967.0         NaN
3              ERP114122                NaN         NaN         NaN
4              SRP162020          GSE120109  30692590.0  PMC6349857
...                  ...                ...         ...         ...
26550          GSE140448      E-GEOD-140448  31776254.0  PMC6925996
26551          GSE137235      E-GEOD-137235  32467224.0  PMC7328513
26552          GSE140426      E-GEOD-140426         NaN         NaN
26553          GSE134244      E-GEOD-134244         NaN         NaN
26554          GSE134247      E-GEOD-134247         NaN         NaN

[26555 rows x 4 columns]

In [14]:
# QC step: de-duplicate datasets present in both SRA and GEO
gsPMC_acc = gsPMC[['SRA_accession_code', 'GEO_accession_code']].dropna()
gsPMC_acc

      SRA_accession_code GEO_accession_code
0              SRP111833          GSE101341
2              SRP062170           GSE71840
4              SRP162020          GSE120109
5              SRP041755           GSE57401
6              SRP153370          GSE117074
...                  ...                ...
26550          GSE140448      E-GEOD-140448
26551          GSE137235      E-GEOD-137235
26552          GSE140426      E-GEOD-140426
26553          GSE134244      E-GEOD-134244
26554          GSE134247      E-GEOD-134247

[17522 rows x 2 columns]

In [15]:
ovAcc = pd.merge(pmcData, gsPMC_acc, how = "left", left_on = "converted_accession", right_on = "SRA_accession_code")
ovAcc

,journal,pmc_ID,accession,converted_accession,SRA_accession_code,GEO_accession_code
0,SAGE Open Med,PMC12833201,GSE85217,GSE85217,NaN,NaN
1,SAGE Open Med,PMC12833201,GSE85212,GSE85212,NaN,NaN
2,Genome Med,PMC12833949,GSE128639,GSE128639,NaN,NaN
3,Genome Med,PMC12833949,GSE214979,GSE214979,NaN,NaN
4,Genome Med,PMC12833949,GSE171964,GSE171964,GSE171964,E-GEOD-171964
...,...,...,...,...,...,...
647611,Nat Struct Mol Biol,PMC2722042,GSE14884,GSE14884,NaN,NaN
647612,bioRxiv,PMC12874027,GSE138852,GSE138852,NaN,NaN
647613,Commun Biol,PMC12647768,PRJNA1341055,SRP630989,NaN,NaN
647614,BMC Geriatr,PMC12681135,PRJNA1255383,SRP581200,NaN,NaN
647615,Nat Biotechnol,PMC12339006,PRJNA1004618,SRP454660,NaN,NaN

In [16]:
# Count the number of SRA datasets also present in GEO
numDupSRA = len(ovAcc["SRA_accession_code"]) - ovAcc["SRA_accession_code"].isna().sum()
print("duplicated SRA datasets: " + str(numDupSRA))

duplicated SRA datasets: 8808

In [17]:
# convert SRA ID of duplicated datasets to GEO ID
ovAccNA = ovAcc.loc[ovAcc["SRA_accession_code"].isna(), :].copy()
ovAcc = ovAcc.loc[~ovAcc["SRA_accession_code"].isna(), :].copy()
ovAcc['converted_accession'] = ovAcc["GEO_accession_code"]
ovAccNA

,journal,pmc_ID,accession,converted_accession,SRA_accession_code,GEO_accession_code
0,SAGE Open Med,PMC12833201,GSE85217,GSE85217,NaN,NaN
1,SAGE Open Med,PMC12833201,GSE85212,GSE85212,NaN,NaN
2,Genome Med,PMC12833949,GSE128639,GSE128639,NaN,NaN
3,Genome Med,PMC12833949,GSE214979,GSE214979,NaN,NaN
5,Genome Med,PMC12833949,GSE148665,GSE148665,NaN,NaN
...,...,...,...,...,...,...
647611,Nat Struct Mol Biol,PMC2722042,GSE14884,GSE14884,NaN,NaN
647612,bioRxiv,PMC12874027,GSE138852,GSE138852,NaN,NaN
647613,Commun Biol,PMC12647768,PRJNA1341055,SRP630989,NaN,NaN
647614,BMC Geriatr,PMC12681135,PRJNA1255383,SRP581200,NaN,NaN
647615,Nat Biotechnol,PMC12339006,PRJNA1004618,SRP454660,NaN,NaN

In [18]:
pmcData = pd.concat([ovAcc, ovAccNA], axis = 0) 
pmcData = pmcData[['journal', 'pmc_ID', 'accession', 'converted_accession']]
pmcData

                    journal       pmc_ID     accession converted_accession
4                Genome Med  PMC12833949     GSE171964       E-GEOD-171964
235           Front Immunol  PMC12832990   PRJNA607333           GSE145505
683                     RNA  PMC12810180    SRX2826536            GSE98935
686                     RNA  PMC12810180    SRX2826543            GSE98935
688                     RNA  PMC12810180    SRX2826535            GSE98935
...                     ...          ...           ...                 ...
647611  Nat Struct Mol Biol   PMC2722042      GSE14884            GSE14884
647612              bioRxiv  PMC12874027     GSE138852           GSE138852
647613          Commun Biol  PMC12647768  PRJNA1341055           SRP630989
647614          BMC Geriatr  PMC12681135  PRJNA1255383           SRP581200
647615       Nat Biotechnol  PMC12339006  PRJNA1004618           SRP454660

[647616 rows x 4 columns]

In [19]:
# QC step: validate our publication-dataset relationships with gold standard table
# merge my PMC ID-accession information with gold standard
# in this table: only those papers in my data AND gold standard
ovPMC = pd.merge(
    gsPMC[
        ['pmc_ID', 'SRA_accession_code', 'GEO_accession_code']
    ],
    pmcData[
        ['pmc_ID', 'accession', 'converted_accession']
    ], 
    on = "pmc_ID", 
    how = "inner")
ovPMC

,pmc_ID,SRA_accession_code,GEO_accession_code,accession,converted_accession
0,PMC5850328,SRP111833,GSE101341,GSE99823,GSE99823
1,PMC5850328,SRP111833,GSE101341,GSE101341,GSE101341
2,PMC6349857,SRP162020,GSE120109,GSE116073,GSE116073
3,PMC6478819,SRP135872,GSE111938,GSE111938,GSE111938
4,PMC4814823,SRP045418,GSE60287,GSE60287,GSE60287
...,...,...,...,...,...
16274,PMC7658810,GSE135892,E-GEOD-135892,GSE135892,E-GEOD-135892
16275,PMC6925996,GSE140448,E-GEOD-140448,GSE140448,E-GEOD-140448
16276,PMC7328513,GSE137235,E-GEOD-137235,GSE137232,GSE137232
16277,PMC7328513,GSE137235,E-GEOD-137235,GSE137234,GSE137234
16278,PMC7328513,GSE137235,E-GEOD-137235,GSE137233,GSE137233

In [20]:
# check for matches between both accession and converted accession, SRA and GEO
ovPMC['match'] = (ovPMC['converted_accession'] == ovPMC['GEO_accession_code']).astype(int)
ovPMC['match'] += (ovPMC['converted_accession'] == ovPMC['SRA_accession_code']).astype(int)
ovPMC['match'] += (ovPMC['accession'] == ovPMC['GEO_accession_code']).astype(int)
ovPMC['match'] += (ovPMC['accession'] == ovPMC['SRA_accession_code']).astype(int)
ovPMC['match'] = ovPMC['match'] > 0
ovPMC

,pmc_ID,SRA_accession_code,GEO_accession_code,accession,converted_accession,match
0,PMC5850328,SRP111833,GSE101341,GSE99823,GSE99823,False
1,PMC5850328,SRP111833,GSE101341,GSE101341,GSE101341,True
2,PMC6349857,SRP162020,GSE120109,GSE116073,GSE116073,False
3,PMC6478819,SRP135872,GSE111938,GSE111938,GSE111938,True
4,PMC4814823,SRP045418,GSE60287,GSE60287,GSE60287,True
...,...,...,...,...,...,...
16274,PMC7658810,GSE135892,E-GEOD-135892,GSE135892,E-GEOD-135892,True
16275,PMC6925996,GSE140448,E-GEOD-140448,GSE140448,E-GEOD-140448,True
16276,PMC7328513,GSE137235,E-GEOD-137235,GSE137232,GSE137232,False
16277,PMC7328513,GSE137235,E-GEOD-137235,GSE137234,GSE137234,False
16278,PMC7328513,GSE137235,E-GEOD-137235,GSE137233,GSE137233,False

In [21]:
# group by paper: if a paper had at least one successful match, we count it as a success
ovPMC_byPap = ovPMC[['pmc_ID', 'match']].groupby("pmc_ID", as_index = False)['match'].max()
ovPMC_byPap = pd.DataFrame(ovPMC_byPap)
# ovPMC_byPap

ovPMC_byPap.loc[~ovPMC_byPap['match'], :]

          pmc_ID  match
21    PMC2871053  False
23    PMC2885365  False
30    PMC2917008  False
36    PMC2990499  False
40    PMC3009665  False
...          ...    ...
6930  PMC8531453  False
6932  PMC8589331  False
6947  PMC9151700  False
6960  PMC9393397  False
6978  PMC9793650  False

[1115 rows x 2 columns]

In [22]:
# count up results and report percentage
totRelsSub = len(ovPMC_byPap['pmc_ID'])
print("Number of papers overlapping with gold standard: " + str(totRelsSub))
totMatching = ovPMC_byPap['match'].sum()
print("Number of such papers validated by gold standard: " + str(totMatching))
pctVal = totMatching / totRelsSub
print("Percent validated: " + str(pctVal))

Number of papers overlapping with gold standard: 6989
Number of such papers validated by gold standard: 5874
Percent validated: 0.8404635856345686

In [23]:
sraAttributes = sraReference

In [24]:
# Convert SRA dates to a universal format
pd.set_option('display.max_columns', 50)
sraAttributes['ReleaseDate'] = sraAttributes['ReleaseDate'].str[0:10]

In [29]:
# Define functions to convert GEO dates to a universal format
def strToMonth(m):
    if(m == 'Jan'):
        return '01'
    elif(m == 'Feb'):
        return '02'
    elif(m == 'Mar'):
        return '03'
    elif(m == 'Apr'):
        return '04'
    elif(m == 'May'):
        return '05'
    elif(m == 'Jun'):
        return '06'
    elif(m == 'Jul'):
        return '07'
    elif(m == 'Aug'):
        return '08'
    elif(m == 'Sep'):
        return '09'
    elif(m == 'Oct'):
        return '10'
    elif(m == 'Nov'):
        return '11'
    elif(m == 'Dec'):
        return '12'
    else:
        return(np.NaN)
    
def convGEODate(d):
    if(type(d) == str):
        mon = strToMonth(d[0:3])
        day = d[4:6]
        yr = d[8:12]
        return yr + '-' + mon + '-' + day
    else:
        return np.nan

In [30]:
# import GEO attribute data and add Series column
geoPlatforms = pd.read_csv('../data/geo_platforms.csv')
geoPlatforms.rename(columns={'Accession':'Platform'}, inplace = True)
techByPlatform = geoPlatforms[['Platform', 'Technology']]

# allData contains metadata matched to GEO series, but lacks 'Technology' column
geoAttributes = pd.merge(allData, techByPlatform, how = 'left', on = 'Platform')
# geoAttributes

In [ ]:
# convert GEO dates to universal format (both sample-level and series-level)
dates_x = []
for i in geoAttributes['Release Date_x']:
    dates_x.append(convGEODate(i))
geoAttributes['Release Date_x'] = dates_x

dates_y = []
for i in geoAttributes['Release Date_y']:
    dates_y.append(convGEODate(i))
geoAttributes['Release Date_y'] = dates_y
# geoAttributes

In [ ]:
# Add a column tagging each accession as GEO or SRA
# E-GEOD (ArrayExpress mirrors of GEO) are treated as GEO

repoList = []

for i in pmcData['converted_accession']:
    if(type(i) == str):
        if('GSE' in i or 'GPL' in i or i.startswith('E-G')):
            repoList.append('GEO')
        elif('SRP' in i or 'ERP' in i or 'DRP' in i):
            repoList.append('SRA')
        else:
            repoList.append(np.nan)
    else:
        repoList.append(np.NaN)
        
pmcData['repository'] = repoList
# pmcData

In [33]:
# add column for paper publish date
pmc_dates = pd.read_csv('../data/pre_filter_dates.csv')
pmc_dates['pmc_ID'] = pmc_dates['File Name'].apply(lambda x: x.split('/')[-1].split('.')[0])
pmc_dates = pmc_dates[['pmc_ID', 'Date']]
pmc_dates.sample(5)

              pmc_ID       Date
2865817  PMC12576562   2025/9/4
789773   PMC11907073  2025/2/05
1683821   PMC8322943  2021/6/30
2595649   PMC6426978   2019/3/6
2552378   PMC6377143   2019/2/2

In [34]:
pmcData = pd.merge(pmcData, pmc_dates, how = 'left', on = 'pmc_ID')
pmcData = pmcData.rename(columns = {'date': 'pmc_date'})

pmcData.sample(5)

,journal,pmc_ID,accession,converted_accession,repository,Date
388967,BMC Bioinformatics,PMC10644638,GSE25462,GSE25462,GEO,2023/9/4
109108,Sci Rep,PMC4650602,PRJNA248163,SRP044705,SRA,2015/05/01
109690,BMC Bioinformatics,PMC4262117,GSE38848,GSE38848,GEO,2014/9/22
429388,BMC Biol,PMC9533543,SRR9304495,SRP201471,SRA,2022/9/27
579918,Mol Psychiatry,PMC11919772,GSE89705,GSE89705,GEO,2024/9/4

In [ ]:
# Get every factor we're interested in from our tables of GEO and SRA metadata...

# take a slice of the GEO and SRA attribute tables with only the info we want
# use sample-level release date (Release Date_x), fall back to series-level (Release Date_y)
# for the ~10k series that have no samples in geo_samples.csv
geoAttributes['geoRelease_combined'] = geoAttributes['Release Date_x'].fillna(geoAttributes['Release Date_y'])
null_before = geoAttributes['Release Date_x'].isna().sum()
null_after = geoAttributes['geoRelease_combined'].isna().sum()
print(f'Recovered {null_before - null_after:,} null GEO release dates via series-level fallback')
print(f'Still null: {null_after:,}')

slicedGEOAtt = geoAttributes[['Series', 'geoRelease_combined', 'Technology', 'Taxonomy_x']]
slicedGEOAtt.columns = ['converted_accession', 'geoRelease', 'geoHardware', 'geoSpecies']
slicedGEOAtt = slicedGEOAtt.drop_duplicates(subset = ['converted_accession'])

slicedSRAAtt = sraAttributes[['SRAStudy', 'ReleaseDate', 'Model', 
                              'LibraryStrategy', 'ScientificName', 
                              'bases', 'avgLength', 'Consent']]
slicedSRAAtt.columns = ['converted_accession', 'sraRelease', 'sraHardware', 
                        'sraLibrary_strategy', 'sraSpecies', 
                        'sraBases', 'sraAvg_length', 'sraAccess']
slicedSRAAtt = slicedSRAAtt.drop_duplicates(subset = ['converted_accession'])

In [36]:
# special case for GEO: make an educated guess on library strategy based on hardware
# These guesses are based on manually checking GEO series IDs that corresponded to various types of hardware

gc = Counter(geoAttributes['Technology'])
ls_guesses = pd.DataFrame.from_dict(gc, orient='index').reset_index()
ls_guesses.columns = ['hardware', 'use_count']
ls_guesses = ls_guesses.drop(labels = ['use_count'], axis = 1)

ls = []

for i in ls_guesses['hardware']:
    if(i == 'high-throughput sequencing'):
        ls.append('RNA-Seq')
    elif(i == 'SAGE NlaIII' or i == 'spotted DNA/cDNA' or i == 'SAGE Sau3A' 
         or i == 'in situ oligonucleotide' or i == 'spotted oligonucleotide' 
         or i == 'antibody' or i == 'MPSS' or i == 'oligonucleotide beads' 
         or i == 'RT-PCR' or i == 'mixed spotted oligonucleotide/cDNA' 
         or i == 'spotted peptide or protein'):
        ls.append('Expression_Array')
    else:
        ls.append(np.nan)
        
ls_guesses.loc[:,'geoLibrary_strategy'] = ls
# ls_guesses

In [37]:
# merge SRA attributes onto pmcData table
mergedSRA = pd.merge(pmcData, slicedSRAAtt, how = 'left', on = 'converted_accession')
mergedSRA = mergedSRA.drop_duplicates()

# merge GEO attributes onto table of pmcData + SRA Attributes
allFactors = pd.merge(mergedSRA, slicedGEOAtt, how = 'left', on = 'converted_accession')
allFactors = pd.merge(allFactors, ls_guesses, how = 'left', left_on = 'geoHardware', right_on = 'hardware')

allFactors = allFactors.dropna(subset = ['converted_accession'])

In [38]:
# clean up columns with factor for both SRA and GEO, rearrange columns
allFactors['species'] = allFactors['sraSpecies'].fillna(allFactors['geoSpecies'])
allFactors = allFactors.drop(labels = ['sraSpecies', 'geoSpecies'], axis = 1)

allFactors['hardware'] = allFactors['sraHardware'].fillna(allFactors['geoHardware'])
allFactors = allFactors.drop(labels = ['sraHardware', 'geoHardware'], axis = 1)

allFactors['library_strategy'] = allFactors['sraLibrary_strategy'].fillna(allFactors['geoLibrary_strategy'])
allFactors = allFactors.drop(labels = ['sraLibrary_strategy', 'geoLibrary_strategy'], axis = 1)

allFactors['repository_date'] = allFactors['sraRelease'].fillna(allFactors['geoRelease'])
allFactors = allFactors.drop(labels = ['sraRelease', 'geoRelease'], axis = 1)

In [39]:
allFactors.head(5)

,journal,pmc_ID,accession,converted_accession,repository,Date,sraBases,sraAvg_length,sraAccess,hardware,species,library_strategy,repository_date
0,Genome Med,PMC12833949,GSE171964,E-GEOD-171964,NaN,2025/11/25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Front Immunol,PMC12832990,PRJNA607333,GSE145505,GEO,2025/12/17,NaN,NaN,NaN,high-throughput sequencing,Homo sapiens,RNA-Seq,2021-04-01
2,RNA,PMC12810180,SRX2826536,GSE98935,GEO,2025/11/20,NaN,NaN,NaN,high-throughput sequencing,Caenorhabditis elegans,RNA-Seq,2017-06-09
3,RNA,PMC12810180,SRX2826543,GSE98935,GEO,2025/11/20,NaN,NaN,NaN,high-throughput sequencing,Caenorhabditis elegans,RNA-Seq,2017-06-09
4,RNA,PMC12810180,SRX2826535,GSE98935,GEO,2025/11/20,NaN,NaN,NaN,high-throughput sequencing,Caenorhabditis elegans,RNA-Seq,2017-06-09

In [40]:
cols = ['journal', 'pmc_ID', 'accession', 'converted_accession', 'repository', 
        'Date', 'repository_date', 'species', 
        'hardware', 'library_strategy', 'sraAvg_length', 'sraBases', 'sraAccess']

allFactors = allFactors[cols]
allFactors

,journal,pmc_ID,accession,converted_accession,repository,Date,repository_date,species,hardware,library_strategy,sraAvg_length,sraBases,sraAccess
0,Genome Med,PMC12833949,GSE171964,E-GEOD-171964,NaN,2025/11/25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Front Immunol,PMC12832990,PRJNA607333,GSE145505,GEO,2025/12/17,2021-04-01,Homo sapiens,high-throughput sequencing,RNA-Seq,NaN,NaN,NaN
2,RNA,PMC12810180,SRX2826536,GSE98935,GEO,2025/11/20,2017-06-09,Caenorhabditis elegans,high-throughput sequencing,RNA-Seq,NaN,NaN,NaN
3,RNA,PMC12810180,SRX2826543,GSE98935,GEO,2025/11/20,2017-06-09,Caenorhabditis elegans,high-throughput sequencing,RNA-Seq,NaN,NaN,NaN
4,RNA,PMC12810180,SRX2826535,GSE98935,GEO,2025/11/20,2017-06-09,Caenorhabditis elegans,high-throughput sequencing,RNA-Seq,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
644953,Cancer Inform,PMC2874327,GDS389,GSE422,GEO,NaN,2003-09-12,Mus musculus,in situ oligonucleotide,Expression_Array,NaN,NaN,NaN
644954,Cancer Inform,PMC2865773,GSE7670,GSE7670,GEO,NaN,2007-08-30,Homo sapiens,in situ oligonucleotide,Expression_Array,NaN,NaN,NaN
644955,Nature,PMC2649681,GSE9996,GSE9996,GEO,NaN,2008-10-30,Arabidopsis thaliana,in situ oligonucleotide,Expression_Array,NaN,NaN,NaN
644956,Nat Struct Mol Biol,PMC2722042,GSE14884,GSE14884,GEO,NaN,2009-06-10,Drosophila melanogaster,in situ oligonucleotide,Expression_Array,NaN,NaN,NaN
644957,bioRxiv,PMC12874027,GSE138852,GSE138852,GEO,NaN,2019-10-16,Homo sapiens,high-throughput sequencing,RNA-Seq,NaN,NaN,NaN

In [41]:
# deduplicate before saving — same paper can appear in multiple archive files
before = len(allFactors)
allFactors = allFactors.drop_duplicates(subset=['pmc_ID', 'converted_accession'])
print(f'Dropped {before - len(allFactors):,} duplicate pmc+accession rows ({before:,} → {len(allFactors):,})')

# save to .csv
allFactors.to_csv('../data/metadata_matrix_raw.csv', index = False)